
language: android
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
  - platform-tools
  - tools
  - tools
  - build-tools-27.0.3
  - android-28
  - extra-android-support
  - extra-android-m2repository

licenses:
    - 'android-sdk-license-.+'

before_script:
  - echo y | android update sdk --no-ui --filter platform-tool
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew build

before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in google-services.json.enc -out google-services.json -d
