language: android
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
android:
  components:
  - platform-tools
  - tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-support
  - extra-android-m2repository
licenses:
- android-sdk-license-.+
before_script:
- echo y | android update sdk --no-ui --filter platform-tool
- yes | sdkmanager "platforms;android-28"
script:
- "./gradlew build"
before_install:
- openssl aes-256-cbc -K $encrypted_3bd8d729af6c_key -iv $encrypted_3bd8d729af6c_iv -in ffc/google-services.json.enc -out ffc/google-services.json -d

